### ISSUE TITLE
自动生成部分待填写参数

### ISSUE THREAD

**Issue by Senyucishi** [syccxcc/MGP-VJ-tool#11]
在生成条目时可以连带生成一些待填写的空参数，省掉<del>复制粘贴</del>手动输入的麻烦

**Comment by lihaohong6** [comment]
> 在生成条目时可以连带生成一些待填写的空参数，省掉~复制粘贴~手动输入的麻烦

LyricsKai参数（左侧颜色，右侧颜色，容器颜色）已添加。如果有更多需求可以回复。
