### ISSUE TITLE
🈶️🈚️🐧支持？😏

### ISSUE THREAD

**Issue by theniceboy** [syccxcc/MGP-VJ-tool#23]

**Comment by lihaohong6** [comment]
CW你怎么来了2333。既然是Python程序跨平台应该是没问题的。专门做个Linux版的build也可以，但是要开虚拟机，很麻烦而且没需求，所以没做。

**Comment by theniceboy** [comment]
@syccxcc feed上看到😂不明觉厉🥸前来支持🙂

我正觉得奇怪，开个windows虚拟机不是挺麻烦的嘛，为啥不直接弄linux的build😂

**Comment by lihaohong6** [comment]
> @syccxcc feed上看到😂不明觉厉🥸前来支持🙂
> 
> 我正觉得奇怪，开个windows虚拟机不是挺麻烦的嘛，为啥不直接弄linux的build😂

其实就是个Python爬虫，没什么技术含量。作用就是快速生成萌百的条目（比如[这个](https://zh.moegirl.org.cn/Booo!)的初版就是自动生成的）。

做build主要是为了其他萌百编辑用起来方便。我自己有mac和Windows 10台式机，所以这两个很好整。有群友用Windows 7用不了Python 3.9或以上，所以我就放了个待办事项，等有时间了用虚拟机试试。

至于linux，愿意用linux的人多半知道怎么用控制台和`pip`，所以大概没什么必要做build 2333。

**Comment by theniceboy** [comment]
有door理
