### ISSUE TITLE
根据罗马音注音

### ISSUE THREAD

**Issue by lihaohong6** [syccxcc/MGP-VJ-tool#24]
VOCADB许多歌曲都有罗马音，可以根据罗马音进行自动注音。Vocaloid Lyrics Wiki也是一个好的注音来源。

注意：
1. fail fast。如果歌词看起来对不上，那多半是选错歌了。
2. 优先处理原歌词，如果原歌词已经有部分注音的话必须特殊处理。

**Comment by theniceboy** [comment]
https://pypi.org/project/pykakasi/

**Comment by lihaohong6** [comment]
> https://pypi.org/project/pykakasi/

是个好东西，可惜太老了，准确度不如[Yahoo的云注音](https://developer.yahoo.co.jp/webapi/jlp/furigana/v2/furigana.html)，比如会把
"君は..."
的君注音成くん，完全不顾上下文2333

**Comment by bhsd-harry** [comment]
但是可以用kakasi处理Yahoo不注音的汉字数字。

**Comment by lihaohong6** [comment]
因功能过于复杂，作为独立项目加入[MGP-VJ-bot](https://github.com/syccxcc/MGP-VJ-bot)
