### ISSUE TITLE
Windows 7兼容

### ISSUE THREAD

**Issue by lihaohong6** [syccxcc/MGP-VJ-tool#8]
目前希望最大的兼容Windows 7的方法就是在Windows 7下使用支持Python 3.8或以下的Pyinstaller打包。需要开虚拟机，很麻烦。

**Comment by ghost** [comment]
https://github.com/nalexandru/api-ms-win-core-path-HACK
currently the simplest way of getting python 3.9, 3.10 installed on Windows 7

**Comment by lihaohong6** [comment]
> https://github.com/nalexandru/api-ms-win-core-path-HACK currently the simplest way of getting python 3.9, 3.10 installed on Windows 7

Seems like a useful hack to bypass this restriction, but it is no longer needed after the downgrade to python 3.8, which makes the project compatible with Windows 7.
