### ISSUE TITLE
自动上传封面至萌娘共享

### ISSUE THREAD

**Issue by lihaohong6** [syccxcc/MGP-VJ-tool#9]
在下载完封面后，向用户展示封面图片并询问是否可以直接将封面上传至萌娘共享，可以省去大概一分钟的选择图片以及填写作者/来源链接/分类的工作。很麻烦，而且省的时间不是那么多。低优先度。

**Comment by Senyucishi** [comment]
有的封面可能分辨率太低，或者是带有黑边，个人比较推荐到画师的推特里找原图。

**Comment by lihaohong6** [comment]
> 有的封面可能分辨率太低，或者是带有黑边，个人比较推荐到画师的推特里找原图。

这种事情很难让程序做。不过确实可以整一个手动复核封面然后
1. 图片合格直接上传
2. 图片不合格手动替换，然后自动上传

不过这个优先度较低，毕竟太费时间了。
